collections:
  editais:
    output: true
  noticias:
    output: true
    sort_by: publicada_em
  projetos:
    output: true

includes_dir: src/_includes
layouts_dir : src/_layouts
destination: src/_site

show_drafts: true
livereload: true
debug: true