collections:
  editais:
    output: true
  noticias:
    output: true
    sort_by: publicada_em
  projetos:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"

includes_dir: src/_includes
layouts_dir : src/_layouts
destination: src/_site

livereload: true
debug: true